services:
  - type: web
    name: lob-trading-system
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_ui.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: RENDER
        value: "true"
